### ISSUE TITLE
Feature request(s) : more gifsicle control

### ISSUE THREAD

**Issue by ChameleonScales** [doakey3/Bligify#1]
Just tried your add-on, it's very cool !
However I'm missing some gifsicle options.
If this addon included --optimize[=LEVEL], --use-colormap and --dither, I would consider using it.
Until then I prefer using commands.
Thanks for this great work you've already done though.

**Comment by doakey3** [comment]
Yeah, that's a good idea and it wouldn't be too hard. I'll see what I can do here in the next couple weeks.

**Comment by doakey3** [comment]
Have a look at [Bligify_dev](https://github.com/doakey3/bligify_dev). Let me know what you think and how it should be improved. It also needs testing to make sure it works right. I might merge it with the main branch in a few days.

**Comment by ChameleonScales** [comment]
Awesome, thanks !

**Comment by doakey3** [comment]
I made more fixes and merged the Bligify_dev with the master branch. I'd still be interested in any recommendations you may have. For now, I'm closing this issue.

**Comment by ChameleonScales** [comment]
That's awesome !
I made some tests and so far I don't see any issue apart from the "FPS Adjust" bug.
I would just use the GROUP_VERTEX icon ![](https://raw.githubusercontent.com/ChameleonScales/Blender-individual-icons/master/PNG-16x16/ICON_GROUP_VERTEX.png) for Dither instead of HAIR ![](https://raw.githubusercontent.com/ChameleonScales/Blender-individual-icons/master/PNG-16x16/ICON_HAIR.png)
