### ISSUE TITLE
Windows 1.3.7 is not rendering a Gif

### ISSUE THREAD

**Issue by dualhammers** [doakey3/Bligify#10]
Add-on installed successfully and sees both executables provided in the .zip.

Upon clicking "Render Gif" the program renders out all the frames and puts them in a (nameofgif)Frames folder, but then nothing occurs. 

Blender console provides no error, it simply saves all the frames and then terminates

**Comment by doakey3** [comment]
Have you tried completely removing the add-on and reinstalling? 

Are you waiting for the add-on to finish? (it renders the frames, then combines them. Combining the frames can take a while if it's a big gif file.)

**Comment by dualhammers** [comment]
Reinstalling did make it work. There were some seeming errors in the console though, so I'm pasting them here in case it prompts you to make any changes. Redacted some folder names as well for job confidentiality

`Converting PNG to GIF frames: [####################] 99.48%convert.exe: UnableToOpenConfigureFile `delegates.xml' @ warning/configure.c/GetConfigureOptions/706.
convert.exe: NoDecodeDelegateForThisImageFormat `INI' @ error/constitute.c/ReadImage/501.
convert.exe: NoImagesDefined `C:\Users\MobileHammer\Google Drive\Progrium\marketing\Social Media Gifs n Vids\EA_Trailer_gifCuts_frames_frames/desktop.gif' @ error/convert.c/ConvertImageCommand/3241.
Converting PNG to GIF frames: [####################] 100.00% DONE
Combining GIF frames into animated GIF...
Traceback (most recent call last):
  File "C:\Users\MobileHammer\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\Bligify_Windows\operators\rendergif.py", line 176, in modal
    self.make_gif(context)
  File "C:\Users\MobileHammer\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\Bligify_Windows\operators\rendergif.py", line 127, in make_gif
    shutil.rmtree(frames_folder)
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\shutil.py", line 393, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\shutil.py", line 391, in _rmtree_unsafe
    os.rmdir(path)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\MobileHammer\\Google Drive\\XXX\\XXX\\XXXX\/'
`

**Comment by doakey3** [comment]
`shutil.rmtree(frames_folder)`

This is the command where bligify tries to delete the frames folder after the GIF is completed. At the bottom of your output it says there was a permission error. That tells me that the program has permission to write to the folder, but not delete anything. Maybe it has to do with it being a Google Drive folder. Try rendering the GIF out to your desktop instead.

**Comment by dualhammers** [comment]
Looks like it was a permissions issue. 

Rendering to the desktop resulted in a gif with no console errors.
