### ISSUE TITLE
Still asking for imagemagick and gifsickle

### ISSUE THREAD

**Issue by Aikonni** [doakey3/Bligify#11]
I installed Bligify_Windows.zip in Blender 2.79 but it didn't show in the Tools tab or anywhere in blender and in the user preferences it keeps telling me I need Imagemagick and gifsickle even after I installed them. Please help :(

**Comment by doakey3** [comment]
What version of Bligify are you using? The latest release is for Blender 2.80 only and will not work for 2.79. 

Use version 1.3.7 for Blender 2.79

**Comment by Aikonni** [comment]
I'm using version 1.3.7 but it's still gives the same error. I tried specifying the path to the executables in the same folder as the add-on to see but it's still the same.

**Comment by doakey3** [comment]
I can't really replicate this problem. Try completely removing the add-on and reinstalling. I have tested it several times on Windows 7 and 10. Otherwise give me more info. A console error message would be nice.

**Comment by Aikonni** [comment]
Here's what I got:
![blender](https://user-images.githubusercontent.com/31870409/50525624-e86c3800-0adc-11e9-8275-41f59e9c450c.png)

**Comment by doakey3** [comment]
That warning in the top right corner is intended to remind the Linux and Mac users that this add-on requires them to install gifsicle and imagemagick separately. It's a warning that isn't supposed to go away.

The fields down below are for the people who prefer to install gifsicle and imagemagick separately and want to specify a custom path to the executable. If you leave those fields blank, Bligify will use the default path.

I've been needing to make another tutorial to walk people through this stuff. The tool tab is supposed to be in the video editor layout of blender, bottom right. Click the tool tab to make the panel appear.

![location](https://i.imgur.com/PYcnU4L.gif)

**Comment by Aikonni** [comment]
Thanks alot! I really appreciate the help! I was checking the tools tab of the 3d view port instead of the video editor. I tried rendering with it according to the gif you posted here https://blenderartists.org/t/bligify-animated-gif-export-import/676565 but it only rendered out my frames in a new folder. It rendered out the PNGs but it didn't convert them to gifs and delete the frames folder.

**Comment by doakey3** [comment]
To answer, I need to have the console output. On Windows, you can open the console by going to the help dropdown and selecting "Toggle System Console". [Like this](https://blender.stackexchange.com/questions/23147/how-do-i-get-the-console-on-windows) I'm guessing either the custom paths you made to the executables are wrong or there's a permission error.

**Comment by Aikonni** [comment]
Thanks, I checked the console and I changed the file directory and that fixed it. Any tips on improving quality and reducing size? The gif I made with the addon is 20mb at 960 x 540

**Comment by doakey3** [comment]
I find that when I am doing a screen-recorded gif, enabling the "Dither Conversion" option often reduces the file size dramatically. Besides that, there aren't any magic bullets. Reduce your frame rate, resolution, colors, etc. If that's not good enough, then whatever you're doing would probably be better done with an mp4.

**Comment by Aikonni** [comment]
Yes it reduced it dramatically, thanks. I also reduced the file dimensions too. Here's the result. Thanks for all your help.
![dribbleinvite](https://user-images.githubusercontent.com/31870409/50558063-1757f900-0ceb-11e9-8f6e-e4dece089a82.gif)
