### ISSUE TITLE
Not working on macOS High Sierra

### ISSUE THREAD

**Issue by Bolos46** [doakey3/Bligify#12]
I installed the Add-On via Homebrew, activated it, restarted Blender 2,8 and when I try to bring a .gif into a Reference image, I just have a pink background. Any ideas what could be wrong ?

Thanks.

**Comment by doakey3** [comment]
I don't have ready access to a mac, so debugging is pretty tough for now... Try opening Blender from a terminal and importing a gif. Does an error message print out?

**Comment by Bolos46** [comment]
Thanks for the help! I tried that but no error prints out when I import a .gif.

**Comment by doakey3** [comment]
Is it just one particular gif or do all gifs do this? Are you able to export a gif ok?

**Comment by Bolos46** [comment]
Actually I don't even see any "Render Gif" option like on the main page documentation, so I'm unable to render any. I'm very new to Blender so maybe there's some obvious things that I missed, sorry if that's the case. I tried to watch the video tutorial but the linked video is unavailable. I also checked the Add-on in the preferences and it seems to be installed properly (checked Gifsicle and Magick paths and there's files). Finally when I installed via Homebrew, I didn't received any error message. Thanks again.

Edit: I tried with other Gifs and still that same pink background.

**Comment by doakey3** [comment]
So you can see a "GIF Import" button, but not a "Render GIF" button? Or is it just grayed out? Where are you clicking to import a GIF?

**Comment by Bolos46** [comment]
Oh I must have been doing it wrong. I don't see any "GIF import" or "render GIF" button. I've just been adding "Reference images" into my scene and thought the add-on would work in the background or something like this when I drop a .gif in the loading menu. Is there anything more I should do once the Add-on is activated in the preferences ? Thanks.

**Comment by doakey3** [comment]
Go to the VSE layout and look to the right side where you should see a small tab that says, "Tools." click that and you should see a drop down tab that says "Bligify." Click that and it should open the Bligify Panel. At the bottom you should see the Render GIF and GIF Import buttons.

![Bligify](https://user-images.githubusercontent.com/16495887/54883270-1b9b3a80-4e32-11e9-816f-6245571e6cd7.png)

**Comment by Bolos46** [comment]
Ah thanks! Found it and managed to import a .gif properly. However, is it possible to move this "Background" object in the 3D space ? It seems to only be present in the VSE layout.

**Comment by doakey3** [comment]
That's outside the scope of the Bligify addon. I'd google, "how to import image sequence into 3D view blender" and go from there.

**Comment by Bolos46** [comment]
Ah okay, sorry for wasting your time and have a nice day.
