### ISSUE TITLE
Tools tab absent in Sequencer/Preview mode

### ISSUE THREAD

**Issue by ChameleonScales** [doakey3/Bligify#14]
The tools tab containing Bligify is not visible when using the Sequencer/Preview mode (the one that stacks both modes in the same area).

Tested on Blender 2.8 with Bligify 1.3.8 and Blender 2.79 with Bligify 1.3.7.

**Comment by doakey3** [comment]
Yeah that is a little annoying, and it's an easy fix. I think I'll wait until Blender 2.80 release candidate 1 is out, then I'll make a new release with this fix (should happen any day now).

**Comment by ChameleonScales** [comment]
it's already out actually
