### ISSUE TITLE
Exports frames instead of a gif.

### ISSUE THREAD

**Issue by Azagwen** [doakey3/Bligify#16]
I've been trying to export a gif by following the instructions, but no matter what I do it keeps exporting frames instead of a .gif .

**Comment by doakey3** [comment]
Bligify works by rendering out individual frames, then combining them into a gif after each frame has rendered. Have you tried waiting for it to finish?

**Comment by Azagwen** [comment]
I've tried again just now, and all it did was export my frames and stop doing stuff, no gif popped anywhere. I don't know what I could be doing wrong 😐

**Comment by doakey3** [comment]
Which operating system are you using? Do you have gifsicle and imagemagick installed?

Do you know how to check the console output? Are there any error messages?

**Comment by Azagwen** [comment]
The last message in the console was this :

`Converting PNG to GIF frames: [--------------------] 0.00%Saved: 'F:\Draws\Projects_3D\Projects_Blender\Cube_text\Hexaza_tg_frames\0084.png'
 Time: 00:01.10 (Saving: 00:00.63)`

But as I said no gif was created in the folder.

How can I check if gifsicle and imagemagick are installed, and how can I install them if they're not ?

**Comment by doakey3** [comment]
If you downloaded the windows version, the gifsicle and imagemagick executables should come with the addon. Otherwise these parts need to be installed separately. As for the issue, you could try rendering the gif out to the desktop. Some users have had issues where folders had different permissions the prevented the addon from changing the image files.

**Comment by Azagwen** [comment]
Turns out I mistakenly downloaded the master branch instead of clocking the "Windows" release link.

Everything seemed to work again after I downloaded the right files until I realized it was deleting the frames folder without creating a gif.

I might be doing something wrong again 🤔
