### ISSUE TITLE
Video unavailable :-(

### ISSUE THREAD

**Issue by RoboDurden** [doakey3/Bligify#17]
"A Tutorial Video is available for an early version of the addon." but the youtube link is dead :-(

Sorry i have never used add-ons. Where do i find the "button" to popup your add-on ?

**Comment by simonschreibt-code** [comment]
The video is still not available :(

**Comment by RoboDurden** [comment]
As i needed transparent videos to add to ActivePresenter i have found another solution:
I export to FFmpeg video with container Quicktime codec "QT rle / QT Animatoin".
Then you can select RGBA in "Output" and in "Shading" i set alpha to "tranpsarent".
Blender internal engine 2.79

**Comment by doakey3** [comment]
Looks like HelloHiHola on youtube made a decent how-to video. I have updated the README to point to his video.
