### ISSUE TITLE
Getting stuck when FPS adjusting twice

### ISSUE THREAD

**Issue by ChameleonScales** [doakey3/Bligify#2]
The first time I perform an FPS adjust on the selected strip(s) it works fine, but if I do it a second time, Blender gets stuck until I kill the app. (of course the strip(s) have to be selected, otherwise it will just change the framerate).
The simple workaround is obviously to delete the generated Speed control(s), move the strip handle(s) to bring back its full length and from there perform the 2nd FPS adjust, but it would be good to at least not have Blender freeze.

**Comment by doakey3** [comment]
FPS Adjust was pretty rickety... I've rewritten it. Thanks for your input. I'll close this issue now.

**Comment by ChameleonScales** [comment]
thanks again !

**Comment by doakey3** [comment]
I noticed yesterday that FPS Adjust was not setting the start frame of the strips correctly. I've corrected this.

**Comment by ChameleonScales** [comment]
Yeah I saw this too and the fix works. It also fixed along the way a bug where the script would stop after rendering the frames (before making the gif) when you had a soft cut from the left of the strip and did an FPS adjust.
So no more bug on sight for me ! (yet)
I must say this add-on is becoming a time saver for me, especially for posting stuff in Blender support forums. All done in one place !
