### ISSUE TITLE
OS support

### ISSUE THREAD

**Issue by ukos-git** [doakey3/Bligify#3]
You should mention somewhere that your program depends on windows.

It should be not so complicated to implement your python code with linux:

* Detect the platform:
```
>>> import platform
>>> platform.system()
'Linux'
```

* convert and gifsicle are native  linux programs:
`apt install gifsicle imagemagick`

* change the code in
[./operators/importgif.py#L89](https://github.com/doakey3/Bligify/blob/00092d738e6df1c46c2faddad7f2e50d933df709/operators/importgif.py#L89)

**Comment by doakey3** [comment]
In the readme, at the bottom of the installation section, there is a note indicating that linux users must install ImageMagick and Gifsicle for the addon to work. 

There is also a warning visible in the Add-ons installation panel inside Blender.

If you think more should be done let me know.

**Comment by ukos-git** [comment]
I have seen the warning:
![image](https://user-images.githubusercontent.com/16167358/28617058-3026a84c-71ff-11e7-9eae-7afdb434997e.png)

I was wondering if the "render gif" button was grayed out due to some os limitations.
![image](https://user-images.githubusercontent.com/16167358/28617344-4534a120-7200-11e7-8398-afd19c382fdc.png)

**Comment by ukos-git** [comment]
sorry. did not see that the work is already [done in line 86 on importgif.py](https://github.com/doakey3/Bligify/blob/00092d738e6df1c46c2faddad7f2e50d933df709/operators/importgif.py#L86):
```
    if sys.platform == 'win32':
        addon_folder = os.path.dirname(__file__)
        converter_path = os.path.join(
            addon_folder, 'executables', 'convert.exe')
        converter = ''.join(['"', converter_path, '"'])
    else:
converter = "convert"
```

so the button is greyed out due to somthing different.

Thank you for you response anyway 👍

**Comment by doakey3** [comment]
The Render GIF Button is grayed out until a strip is available to render in the sequencer. 

Hey, I just realized that the FPS Adjust Button really should be grayed out until a strip is available too. I'll go ahead and add that change.

**Comment by ukos-git** [comment]
Thank you for the hint.

[shift+a](https://wiki.blender.org/index.php/Meta:Sanbox/Doc:2.6/Manual/Sequencer/Strips/Add-Strips) is doing the job if anyone runs into the same problem.
