### ISSUE TITLE
Import gif without modifying project?

### ISSUE THREAD

**Issue by madmuffinz** [doakey3/Bligify#5]
I was making a project and I imported the gif thinking it would only import the frames, but the project had been modified to fit the resolution of the gif, and frame rate?
Is there a way to just import the gif's frames without affecting the project?

**Comment by doakey3** [comment]
Bligify will convert your GIF into PNG frames, then import the frames. The frames are stored in the same folder as the GIF that you import. The frame rate and resolution are automatically adjusted for convenience for most users.

You could open a new instance of Blender, use Bligify to import the GIF, then import the PNG frames into your project without affecting the framerate or resolution.

**Comment by madmuffinz** [comment]
Ah I get the workaround, but would this be considered for future releases?

**Comment by doakey3** [comment]
I've made an update. Now when you click the GIF import button, look for a checkbox to the left that says "Adjust Scene For GIF" and uncheck it. This will bypass the function for updating the resolution and the framerate of the scene. This solution ok?

**Comment by madmuffinz** [comment]
I do not see it when I select a gif in the proprties.
It is 1.3.4 right?
Screenshot:
http://i.xomf.com/mzfzg.png

**Comment by doakey3** [comment]
It is 1.3.4. I just tested this on my windows 7 and my linux machines and it's working properly. Did you try uninstalling the old version, then installing the new one?
Screenshot:
https://i.imgur.com/5q0p3UF.jpg

**Comment by madmuffinz** [comment]
I guess doing that worked! I was using Win7 too.
I _think_ I remember uninstalling the addon at a time and reinstalled the addon, but I am not too sure.
Either way it's working! thank you. This is a very helpful feature
