### ISSUE TITLE
Cannot Enable Windows Version in 2.79

### ISSUE THREAD

**Issue by dualhammers** [doakey3/Bligify#9]
![image](https://user-images.githubusercontent.com/7495830/49832133-11f23900-fd53-11e8-8654-90639d408147.png)

Errors displayed appear when trying to enable the add-on after installing from .zip file.

I am using version 1.3.8

**Comment by dualhammers** [comment]
Update:

Using 1.3.7 the program works correctly. Perhaps there is a way to indicate on the release page that the .3.8 version only works with 2.8?

**Comment by doakey3** [comment]
The title of the release for 1.3.8 is "1.3.8 Release for Blender 2.8". No 2.80 add-on releases are going to work for 2.79 and below--not just for Bligify, but for all add-ons.
